### ISSUE TITLE
Add support for setting annotations

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit#1441] opened 2017-10-24 15:24 UTC
Based on discussion with @bassosimone we would like to be able to flag references to another report by setting a special annotation called:

```
report_id_refs: ["id_one", "id_two"]
```

It seems like the MK API does not expose the ability to set annotations, this ticket is about adding support for that.

**Comment by bassosimone** [comment] 2017-11-03 09:27
Duplicate of #1376

**Closed** 2017-11-03 09:53 UTC
Labels: duplicate, enhancement
