### ISSUE TITLE
on_entry Json use wrong date formatter

### ISSUE THREAD

**Issue by xanscale** [measurement-kit/measurement-kit#1644] opened 2018-07-04 15:55 UTC
inside on_entry this is the date returned:
```
"measurement_start_time": "2018-07-04 15:22:26",
"test_start_time": "2018-07-04 15:22:23",
```

this date format are in local time but date are in UTC time zone. the correct format are:
```
"measurement_start_time": "2018-07-04 15:22:26Z",
"test_start_time": "2018-07-04 15:22:23Z",
```

just add a "Z" at the end

ref https://www.w3.org/TR/NOTE-datetime

**Comment by bassosimone** [comment] 2018-07-04 16:09
So, this format is the actual format that we chose to use in the OONI specification): [the date and time is expressed as a string, in UTC, and the `Z` is omitted](https://github.com/ooni/spec/blob/master/data-formats/df-000-base.md). My recollection of the discussion we had was that we were going to omit the `Z` because it was already implemented as such in code, and we were going to leave adding the `Z` as a future improvement. Is this issue creating real technical difficulties or is it just an argument stating that it's a non obvious convention?

**Comment by bassosimone** [comment] 2018-07-04 16:10
@hellais added on slack:
> It probably should have also used T instead of space as a separator

**Comment by hellais** [comment] 2018-07-04 16:22
This issue is actually related to the OONI data format and is a duplicate of: https://github.com/ooni/spec/issues/74.

**Comment by bassosimone** [comment] 2018-07-04 16:33
Yeah, I guess we can close this and defer to ooni/spec#74 for further details.

**Closed by bassosimone** 2018-07-04 16:33 UTC
Labels: duplicate
