### ISSUE TITLE
travis: create build matrix

### ISSUE THREAD

**Issue by AntonioLangiu** [measurement-kit/measurement-kit#322] opened 2015-12-20 11:44 UTC
With the new enhancement we have now coverage and Valgrind support in Travis. All this features slow down the compilation on Travis, so they should be done in different builds using a build matrix.

**Comment by bassosimone** [comment] 2015-12-22 15:33
I don't think that the problem is speed only. I think what is more sane is to have different means to do testing because it creates too much confounding factors to have a single mechanism. Suppose we find something broken in the tests (as we did), if we have one mechanism with coverage, valgrind etc, how do we know the root cause?

**Comment by AntonioLangiu** [comment] 2016-01-03 13:24
This is quite done. I'm opening a pull request to discuss the changes.

**Comment by bassosimone** [comment] 2016-03-17 22:39
We can close since now #328 has been merged!

**Closed by bassosimone** 2016-03-17 22:39 UTC
Labels: enhancement, help wanted
