### ISSUE TITLE
Record how much bandwidth measurement-kit is using when running a test

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit#1283] opened 2017-07-25 15:08 UTC
A recurring question we get from ooniprobe users is: "How much bandwidth does ooniprobe use?". It would be nice if we could actually give a better answer than "It depends on this and that", but instead say "Look at the bandwidth consumption tab".

To this end it would be great if measurement-kit kept track of how much bandwidth it's using for:

* Running tests
* Uploading measurement results

I think it's not the end of the world if this bandwidth estimation is not 100% accurate (for example it doesn't take into account the bandwidth used for doing DNS queries), but just calculates the things that consume most bandwidth (HTTP(s) requests).

**Comment by bassosimone** [comment] 2017-08-05 14:28
Duplicate of #1105

**Closed by bassosimone** 2017-08-05 14:28 UTC
Labels: duplicate, enhancement, usability, wishlist
