### ISSUE TITLE
Add Boolean giving the test status

### ISSUE THREAD

**Issue by lorenzoPrimi** [measurement-kit/measurement-kit#466] opened 2016-04-13 10:42 UTC
Needed for a quick visualization of the status test in the mobile app.

**Comment by AntonioLangiu** [comment] 2016-04-13 10:44
I think this issue is related to #455

**Comment by bassosimone** [comment] 2016-04-16 18:34
Closing because this is a duplicate of #455.

**Closed by bassosimone** 2016-04-16 18:34 UTC
Labels: enhancement
